name: vim-sagetex-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  # Core software
  - python=3.10
  - sagemath  # Remove version number - use latest
  - vim
  - make
  - git
  
  # LaTeX packages (these have different names in conda)
  - texlive-core
  
  # Jupyter for the interface
  - jupyterlab=3
  - notebook
  
  # Additional tools
  - pip
  - pip:
    - sagetex
